name: download and upload video

on:
  schedule:
    - cron: "* */2 * * *"
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  BILI_UP_VER: v0.1.14

jobs:
  main:
    concurrency: download-and-upload
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: install dependency
        run: |
          cat>/etc/apt/ources.list<<EOF
          deb http://mirrors.aliyun.com/ubuntu/ impish main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ impish main restricted universe multiverse

          deb http://mirrors.aliyun.com/ubuntu/ impish-security main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ impish-security main restricted universe multiverse

          deb http://mirrors.aliyun.com/ubuntu/ impish-updates main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ impish-updates main restricted universe multiverse

          deb http://mirrors.aliyun.com/ubuntu/ impish-proposed main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ impish-proposed main restricted universe multiverse

          deb http://mirrors.aliyun.com/ubuntu/ impish-backports main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ impish-backports main restricted universe multiverse
          EOF
          sudo apt-get update
          sudo apt-get upgrade
 
          sudo apt install ffmpeg -y
          pip install -r requirements.txt
          wget https://github.com/ForgQi/biliup-rs/releases/download/$BILI_UP_VER/biliupR-$BILI_UP_VER-x86_64-linux.tar.xz
          tar xvf biliupR-$BILI_UP_VER-x86_64-linux.tar.xz
          sudo mv biliupR-$BILI_UP_VER-x86_64-linux/biliup /usr/local/bin/
          sudo chmod +x /usr/local/bin/biliup
      - name: main logic
        env:
          GIST_ID: ${{secrets.GIST_ID}}
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
        run: python upload.py $GIT_TOKEN $GIST_ID
